
services:
  web:
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.development
    volumes:
      - .:/app
      - shellhistory:/root

volumes:
  shellhistory:
