
services:
  web:
    entrypoint: ["/app/entrypoint.dev.sh"]
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.development
    volumes:
      - .:/app
      - shellhistory:/root
    ports:
      - "8000:8000"

  nginx:
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/templates/default.conf.template:ro

volumes:
  shellhistory:
