# Generated by Django 5.2.10 on 2026-02-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_payment_status_payment_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
