# Generated by Django 5.2.13 on 2026-05-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_address_created_at_address_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
